In [4]:
# comparing two files from 6-24 checks
import pandas as pd

#df = pd.read_csv("tdm-preprocessed-6-28.csv")
check = pd.read_csv("cabs_after_previous_mo_calculation.csv")

C:\Users\abb2603\AppData\Local\Temp\ipykernel_12988\94995830.py:5: DtypeWarning: Columns (12,18,20,21,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  check = pd.read_csv("cabs_after_previous_mo_calculation.csv")

In [16]:
check[check["CLEAN_ID"] == "61HCGS001176CMWL"].to_csv("61HCGS001176CMWL.csv")

In [7]:
check.columns

Index(['CLEAN_ID', 'CMPY_NO', 'CMPY_NO_COUNT', 'STATE', 'CIRCUIT_NO',
       'NC_PRODUCT_CD', 'NCI', 'BILL_MONTH_DT', 'ACNA', 'JURIS_CD',
       'TOTAL_MRC', 'PRIMARY_CARRIER_NAME', 'PLAN_ID', 'WIRELESS', 'SVC_GROUP',
       'PRODUCT', 'ETHERNET_TYPE', 'UNI_MBPS', 'ADJ', 'EVC_MBPS', 'NNI',
       'FIRST_BILL_MONTH_DT', 'LAST_BILL_MONTH_DT', 'MILEAGE_MRC', 'ADDR',
       'CUST', 'IXC_NAME', 'SWC', 'INSTALL_DT', 'DISCONNECT_DT',
       'TERM_START_DT', 'TERM_END_DT', 'SW_SPL_IND', 'ROWNUM', 'SWC8',
       'CARRIER_LAST_MO_SAME'],
      dtype='object')

In [8]:
check[check["CLEAN_ID"] == "61HCGS001176CMWL"][["CLEAN_ID", "BILL_MONTH_DT", "PRIMARY_CARRIER_NAME", "CARRIER_LAST_MO_SAME", "CMPY_NO_COUNT"]]

# columns we used for sorting - export snippet of clean ID - make sure properly filled

,CLEAN_ID,BILL_MONTH_DT,PRIMARY_CARRIER_NAME,CARRIER_LAST_MO_SAME,CMPY_NO_COUNT
6435098,61HCGS001176CMWL,2019-01-01,AT&T,1,1.0
6435099,61HCGS001176CMWL,2019-01-01,CENTURYLINK,0,1.0
6435100,61HCGS001176CMWL,2019-02-01,AT&T,0,1.0
6435101,61HCGS001176CMWL,2019-02-01,CENTURYLINK,0,1.0
6435102,61HCGS001176CMWL,2019-03-01,CENTURYLINK,1,1.0
6435103,61HCGS001176CMWL,2019-03-01,AT&T,0,1.0
6435104,61HCGS001176CMWL,2019-04-01,AT&T,1,1.0
6435105,61HCGS001176CMWL,2019-04-01,CENTURYLINK,0,1.0
6435106,61HCGS001176CMWL,2019-05-01,CENTURYLINK,1,1.0
6435107,61HCGS001176CMWL,2019-05-01,AT&T,0,1.0
6435108,61HCGS001176CMWL,2019-06-01,AT&T,1,1.0
6435109,61HCGS001176CMWL,2019-06-01,CENTURYLINK,0,1.0
6435110,61HCGS001176CMWL,2019-07-01,CENTURYLINK,1,1.0
6435111,61HCGS001176CMWL,2019-07-01,AT&T,0,1.0
6435112,61HCGS001176CMWL,2019-08-01,CENTURYLINK,0,1.0
6435113,61HCGS001176CMWL,2019-08-01,AT&T,0,1.0
6435114,61HCGS001176CMWL,2019-09-01,AT&T,1,1.0
6435115,61HCGS001176CMWL,2019-09-01,CENTURYLINK,0,1.0
6435116,61HCGS001176CMWL,2019-10-01,AT&T,0,1.0
6435117,61HCGS001176CMWL,2019-10-01,CENTURYLINK,0,1.0
6435118,61HCGS001176CMWL,2019-11-01,CENTURYLINK,1,1.0
6435119,61HCGS001176CMWL,2019-12-01,CENTURYLINK,1,1.0
6435120,61HCGS001176CMWL,2020-01-01,CENTURYLINK,1,1.0
6435121,61HCGS001176CMWL,2020-02-01,CENTURYLINK,1,1.0
6435122,61HCGS001176CMWL,2020-03-01,CENTURYLINK,1,1.0
6435123,61HCGS001176CMWL,2020-04-01,CENTURYLINK,1,1.0
6435124,61HCGS001176CMWL,2020-05-01,CENTURYLINK,1,1.0
6435125,61HCGS001176CMWL,2020-06-01,CENTURYLINK,1,1.0
6435126,61HCGS001176CMWL,2020-07-01,CENTURYLINK,1,1.0
6435127,61HCGS001176CMWL,2020-08-01,CENTURYLINK,1,1.0
6435128,61HCGS001176CMWL,2020-09-01,CENTURYLINK,1,1.0
6435129,61HCGS001176CMWL,2020-10-01,CENTURYLINK,1,1.0
6435130,61HCGS001176CMWL,2020-11-01,CENTURYLINK,1,1.0
6435131,61HCGS001176CMWL,2020-12-01,CENTURYLINK,1,1.0
6435132,61HCGS001176CMWL,2021-01-01,CENTURYLINK,1,1.0
6435133,61HCGS001176CMWL,2021-02-01,CENTURYLINK,1,1.0
6435134,61HCGS001176CMWL,2021-03-01,CENTURYLINK,1,1.0
6435135,61HCGS001176CMWL,2021-04-01,CENTURYLINK,1,1.0
6435136,61HCGS001176CMWL,2021-05-01,CENTURYLINK,1,1.0
6435137,61HCGS001176CMWL,2021-06-01,CENTURYLINK,1,1.0
6435138,61HCGS001176CMWL,2021-07-01,CENTURYLINK,1,1.0
6435139,61HCGS001176CMWL,2021-08-01,CENTURYLINK,1,1.0

In [17]:
# OLD ONE BELOW don't run yet
check[check["CLEAN_ID"] == "61HCGS001176CMWL"][["CLEAN_ID", "BILL_MONTH_DT", "TOTAL_MRC","CARRIER_LAST_MO_SAME","LAST_BILL_MONTH_DT", "PRIMARY_CARRIER_NAME"]]

# columns we used for sorting - export snippet of clean ID - make sure properly filled

,CLEAN_ID,BILL_MONTH_DT,TOTAL_MRC,CARRIER_LAST_MO_SAME,LAST_BILL_MONTH_DT,PRIMARY_CARRIER_NAME
6435098,61HCGS001176CMWL,2019-01-01,547.12,1,NaN,AT&T
6435099,61HCGS001176CMWL,2019-01-01,547.12,0,NaN,CENTURYLINK
6435100,61HCGS001176CMWL,2019-02-01,547.12,0,NaN,AT&T
6435101,61HCGS001176CMWL,2019-02-01,547.12,0,NaN,CENTURYLINK
6435102,61HCGS001176CMWL,2019-03-01,629.20,1,NaN,CENTURYLINK
6435103,61HCGS001176CMWL,2019-03-01,629.20,0,NaN,AT&T
6435104,61HCGS001176CMWL,2019-04-01,629.20,1,NaN,AT&T
6435105,61HCGS001176CMWL,2019-04-01,629.20,0,NaN,CENTURYLINK
6435106,61HCGS001176CMWL,2019-05-01,629.20,1,NaN,CENTURYLINK
6435107,61HCGS001176CMWL,2019-05-01,629.20,0,NaN,AT&T
6435108,61HCGS001176CMWL,2019-06-01,629.20,1,NaN,AT&T
6435109,61HCGS001176CMWL,2019-06-01,629.20,0,NaN,CENTURYLINK
6435110,61HCGS001176CMWL,2019-07-01,629.20,1,NaN,CENTURYLINK
6435111,61HCGS001176CMWL,2019-07-01,629.20,0,NaN,AT&T
6435112,61HCGS001176CMWL,2019-08-01,629.20,0,NaN,CENTURYLINK
6435113,61HCGS001176CMWL,2019-08-01,629.20,0,NaN,AT&T
6435114,61HCGS001176CMWL,2019-09-01,629.20,1,NaN,AT&T
6435115,61HCGS001176CMWL,2019-09-01,629.20,0,NaN,CENTURYLINK
6435116,61HCGS001176CMWL,2019-10-01,538.99,0,NaN,AT&T
6435117,61HCGS001176CMWL,2019-10-01,538.99,0,NaN,CENTURYLINK
6435118,61HCGS001176CMWL,2019-11-01,360.83,1,NaN,CENTURYLINK
6435119,61HCGS001176CMWL,2019-12-01,360.83,1,NaN,CENTURYLINK
6435120,61HCGS001176CMWL,2020-01-01,360.83,1,NaN,CENTURYLINK
6435121,61HCGS001176CMWL,2020-02-01,360.83,1,NaN,CENTURYLINK
6435122,61HCGS001176CMWL,2020-03-01,360.83,1,NaN,CENTURYLINK
6435123,61HCGS001176CMWL,2020-04-01,414.95,1,NaN,CENTURYLINK
6435124,61HCGS001176CMWL,2020-05-01,414.95,1,NaN,CENTURYLINK
6435125,61HCGS001176CMWL,2020-06-01,414.95,1,NaN,CENTURYLINK
6435126,61HCGS001176CMWL,2020-07-01,414.95,1,NaN,CENTURYLINK
6435127,61HCGS001176CMWL,2020-08-01,414.95,1,NaN,CENTURYLINK
6435128,61HCGS001176CMWL,2020-09-01,414.95,1,NaN,CENTURYLINK
6435129,61HCGS001176CMWL,2020-10-01,414.95,1,NaN,CENTURYLINK
6435130,61HCGS001176CMWL,2020-11-01,414.95,1,NaN,CENTURYLINK
6435131,61HCGS001176CMWL,2020-12-01,414.95,1,NaN,CENTURYLINK
6435132,61HCGS001176CMWL,2021-01-01,414.95,1,NaN,CENTURYLINK
6435133,61HCGS001176CMWL,2021-02-01,414.95,1,NaN,CENTURYLINK
6435134,61HCGS001176CMWL,2021-03-01,518.65,1,NaN,CENTURYLINK
6435135,61HCGS001176CMWL,2021-04-01,518.65,1,NaN,CENTURYLINK
6435136,61HCGS001176CMWL,2021-05-01,518.65,1,NaN,CENTURYLINK
6435137,61HCGS001176CMWL,2021-06-01,518.65,1,NaN,CENTURYLINK
6435138,61HCGS001176CMWL,2021-07-01,518.65,1,NaN,CENTURYLINK
6435139,61HCGS001176CMWL,2021-08-01,518.65,1,2021-08-01,CENTURYLINK

In [12]:
df[df["CLEAN_ID"] == "61HCGS001176CMWL"][["CLEAN_ID", "BILL_MONTH_DT", "PRIMARY_CARRIER_NAME", "CARRIER_LAST_MO_SAME"]]

# columns we used for sorting - export snippet of clean ID - make sure properly filled

,CLEAN_ID,BILL_MONTH_DT,PRIMARY_CARRIER_NAME,CARRIER_LAST_MO_SAME
6543,61HCGS001176CMWL,2019-01-01,AT&T,1
183278,61HCGS001176CMWL,2019-02-01,LUMEN,0
402204,61HCGS001176CMWL,2019-03-01,LUMEN,1
479642,61HCGS001176CMWL,2019-04-01,AT&T,1
665153,61HCGS001176CMWL,2019-05-01,LUMEN,1
805234,61HCGS001176CMWL,2019-06-01,AT&T,1
896959,61HCGS001176CMWL,2019-07-01,LUMEN,1
989580,61HCGS001176CMWL,2019-08-01,AT&T,0
1097675,61HCGS001176CMWL,2019-09-01,AT&T,1
1196624,61HCGS001176CMWL,2019-10-01,LUMEN,0
1393371,61HCGS001176CMWL,2019-11-01,LUMEN,1
1515716,61HCGS001176CMWL,2019-12-01,LUMEN,1
1599194,61HCGS001176CMWL,2020-01-01,LUMEN,1
1744141,61HCGS001176CMWL,2020-02-01,LUMEN,1
1844577,61HCGS001176CMWL,2020-03-01,LUMEN,1
1961247,61HCGS001176CMWL,2020-04-01,LUMEN,1
2037901,61HCGS001176CMWL,2020-05-01,LUMEN,1
2175310,61HCGS001176CMWL,2020-06-01,LUMEN,1
2270636,61HCGS001176CMWL,2020-07-01,LUMEN,1
2376526,61HCGS001176CMWL,2020-08-01,LUMEN,1
2404444,61HCGS001176CMWL,2020-09-01,LUMEN,1
2585392,61HCGS001176CMWL,2020-10-01,LUMEN,1
2636143,61HCGS001176CMWL,2020-11-01,LUMEN,1
2730267,61HCGS001176CMWL,2020-12-01,LUMEN,1
2781633,61HCGS001176CMWL,2021-01-01,LUMEN,1
2876842,61HCGS001176CMWL,2021-02-01,LUMEN,1
3031806,61HCGS001176CMWL,2021-03-01,LUMEN,1
3112729,61HCGS001176CMWL,2021-04-01,LUMEN,1
3143745,61HCGS001176CMWL,2021-05-01,LUMEN,1
3256954,61HCGS001176CMWL,2021-06-01,LUMEN,1
3349826,61HCGS001176CMWL,2021-07-01,LUMEN,1
3435138,61HCGS001176CMWL,2021-08-01,LUMEN,1

In [7]:
df.reset_index(inplace=True)

index                            0
Unnamed: 0                       0
CLEAN_ID                   0010011
BILL_MONTH_DT           2019-01-01
FIRST_BILL_MONTH_DT            NaN
LAST_BILL_MONTH_DT             NaN
CMPY_NO_COUNT                  1.0
STATE                           CA
TOTAL_MRC                   686.62
PRIMARY_CARRIER_NAME          AT&T
PLAN_ID                        NaN
WIRELESS                  WIRELINE
SVC_GROUP                  TDM_DS1
PRODUCT                    TDM/OCN
SWC8                      EKGVCAXJ
INSTALL_DT              2004-09-15
DISCONNECT_DT                  NaN
TERM_START_DT                  NaN
TERM_END_DT                    NaN
ORIG_END_DT             2007-09-15
PNUM                           NaN
MO_LEFT                     -138.0
SEM_LEFT                     -23.0
STATUS                      ACTIVE
Name: 0, dtype: object

In [8]:
df

,index,Unnamed: 0,CLEAN_ID,BILL_MONTH_DT,FIRST_BILL_MONTH_DT,LAST_BILL_MONTH_DT,CMPY_NO_COUNT,STATE,TOTAL_MRC,PRIMARY_CARRIER_NAME,...,SWC8,INSTALL_DT,DISCONNECT_DT,TERM_START_DT,TERM_END_DT,ORIG_END_DT,PNUM,MO_LEFT,SEM_LEFT,STATUS
0,0,0,0010011,2019-01-01,NaN,NaN,1.0,CA,686.62,AT&T,...,EKGVCAXJ,2004-09-15,NaN,NaN,NaN,2007-09-15,NaN,-138.0,-23.0,ACTIVE
1,94615,94755,33HCGS545574FTNC,2019-01-01,NaN,NaN,1.0,MI,308.09,AT&T,...,LNDNMIXG,2013-09-09,NaN,2013-09-09,2023-09-09,2023-09-09,VTA120TV30001,57.0,9.0,ACTIVE
2,94614,94754,104T3LNBHCAXFK04LNBHCAXFW11,2019-01-01,NaN,NaN,1.0,CA,180.52,TPX,...,LNBHCAXF,2009-11-13,NaN,NaN,NaN,2012-11-13,NaN,-75.0,-12.0,ACTIVE
3,94613,94753,63HCGS557910FTNC,2019-01-01,NaN,NaN,1.0,NC,383.01,AT&T,...,SEVRNCXA,2014-02-10,NaN,NaN,NaN,2017-02-10,NaN,-23.0,-4.0,ACTIVE
4,94612,94752,33HCGS545630FTNC,2019-01-01,NaN,NaN,1.0,MI,220.76,AT&T,...,WMTNMIXG,2013-09-04,NaN,2013-09-04,2023-09-04,2023-09-04,VTA120TV30001,57.0,9.0,ACTIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5001312,4984421,4995692,81HCGS977072GTEW,2024-04-01,NaN,NaN,1.0,CA,3764.02,AT&T,...,BLPKCAXF,2015-10-31,NaN,NaN,NaN,2018-10-31,NaN,-66.0,-11.0,ACTIVE
5001313,4984420,4995691,81HCGS977074GTEW,2024-04-01,NaN,NaN,1.0,CA,3764.02,AT&T,...,BLPKCAXF,2015-10-31,NaN,NaN,NaN,2018-10-31,NaN,-66.0,-11.0,ACTIVE
5001314,4984419,4995690,81HCGS977075GTEW,2024-04-01,NaN,NaN,1.0,CA,3764.02,AT&T,...,BLPKCAXF,2015-10-31,NaN,NaN,NaN,2018-10-31,NaN,-66.0,-11.0,ACTIVE
5001315,4984417,4995688,81HCGS977200GTEW,2024-04-01,NaN,NaN,1.0,CA,3759.12,VERIZON,...,MRHLCAXF,2015-10-22,NaN,NaN,NaN,2018-10-22,NaN,-66.0,-11.0,ACTIVE
5001316,5001316,5012652,36HCGS573327FTNC,2024-04-01,NaN,2024-04-01,1.0,OH,2405.95,AT&T,...,MTRSOHXA,2012-08-06,2024-04-02,NaN,NaN,2015-08-06,NaN,-105.0,-17.0,DC

In [15]:
# function to see if primary carrier name is the same as previous month for each clean ID
def check_carrier_previous_month(cabs):
    """Create new column to denote if PRIMARY_CARRIER_NAME is the same in previous month.
    If yes, value is 1.
    If no, value is 0."""
    cabs["SAME_CARRIER_PREV_MONTH"] = cabs["PRIMARY_CARRIER_NAME"] == cabs.groupby("CLEAN_ID")["PRIMARY_CARRIER_NAME"].shift(1)
    cabs["SAME_CARRIER_PREV_MONTH"] = cabs["SAME_CARRIER_PREV_MONTH"].astype(int)

    # if row has first instance of a clean ID, set SAME_CARRIER_PREV_MONTH to 1
    cabs.loc[cabs.groupby("CLEAN_ID")["PRIMARY_CARRIER_NAME"].shift(1).isnull(), "SAME_CARRIER_PREV_MONTH"] = 1

    return cabs

df = check_carrier_previous_month(df)

In [17]:
df[df["SAME_CARRIER_PREV_MONTH"] == 0][["CLEAN_ID", "BILL_MONTH_DT", "PRIMARY_CARRIER_NAME", "SAME_CARRIER_PREV_MONTH"]]

,CLEAN_ID,BILL_MONTH_DT,PRIMARY_CARRIER_NAME,SAME_CARRIER_PREV_MONTH
293203,45HCGS008667FTNC,2019-03-01,WINDSTREAM,0
335547,101T1ZFLKALFLXA95HTAMPFLXAW23,2019-03-01,VERIZON,0
352077,63HCGS684273FTNC,2019-03-01,VERIZON,0
352084,63HCGS684274FTNC,2019-03-01,VERIZON,0
352107,63HCGS684272FTNC,2019-03-01,VERIZON,0
...,...,...,...,...
4791568,101T1ZFCMRLCAXFDC0WLANCA01W25,2023-09-01,TPX,0
4886576,101T1ZFFRFDCT00DC0SMFRCT01WP2,2023-12-01,VERIZON,0
4892050,101T1ZFCMRLCAXFDC0WLANCA01W25,2023-12-01,VERIZON,0
4975905,101T1ZFCMRLCAXFDC0WLANCA01W25,2024-03-01,TPX,0
4979899,101T1ZFCMRLCAXFDC0WLANCA01W25,2024-04-01,VERIZON,0

In [20]:
df[df["CLEAN_ID"] == "101T1ZFLKALFLXA95HTAMPFLXAW23"][["CLEAN_ID", "BILL_MONTH_DT", "PRIMARY_CARRIER_NAME", "SAME_CARRIER_PREV_MONTH"]]

,CLEAN_ID,BILL_MONTH_DT,PRIMARY_CARRIER_NAME,SAME_CARRIER_PREV_MONTH
125851,101T1ZFLKALFLXA95HTAMPFLXAW23,2019-01-01,LUMEN,1
166050,101T1ZFLKALFLXA95HTAMPFLXAW23,2019-02-01,LUMEN,1
335547,101T1ZFLKALFLXA95HTAMPFLXAW23,2019-03-01,VERIZON,0
429535,101T1ZFLKALFLXA95HTAMPFLXAW23,2019-04-01,VERIZON,1
648973,101T1ZFLKALFLXA95HTAMPFLXAW23,2019-05-01,VERIZON,1
...,...,...,...,...
4865633,101T1ZFLKALFLXA95HTAMPFLXAW23,2023-12-01,VERIZON,1
4896184,101T1ZFLKALFLXA95HTAMPFLXAW23,2024-01-01,VERIZON,1
4948722,101T1ZFLKALFLXA95HTAMPFLXAW23,2024-02-01,VERIZON,1
4975506,101T1ZFLKALFLXA95HTAMPFLXAW23,2024-03-01,VERIZON,1
4977790,101T1ZFLKALFLXA95HTAMPFLXAW23,2024-04-01,VERIZON,1

In [16]:
df[["CLEAN_ID", "BILL_MONTH_DT", "PRIMARY_CARRIER_NAME", "SAME_CARRIER_PREV_MONTH"]].sort_values(["CLEAN_ID", "BILL_MONTH_DT"]).head(50)

        CLEAN_ID BILL_MONTH_DT PRIMARY_CARRIER_NAME  SAME_CARRIER_PREV_MONTH
0        0010011    2019-01-01                 AT&T                        1
238463   0010011    2019-02-01                 AT&T                        1
291295   0010011    2019-03-01                 AT&T                        1
548892   0010011    2019-04-01                 AT&T                        1
676401   0010011    2019-05-01                 AT&T                        1
811569   0010011    2019-06-01                 AT&T                        1
868027   0010011    2019-07-01                 AT&T                        1
987727   0010011    2019-08-01                 AT&T                        1
1079931  0010011    2019-09-01                 AT&T                        1
1192113  0010011    2019-10-01                 AT&T                        1
1386470  0010011    2019-11-01                 AT&T                        1
1495892  0010011    2019-12-01                 AT&T                        1
1640848  0010011    2020-01-01                 AT&T                        1
1660959  0010011    2020-02-01                 AT&T                        1
1767085  0010011    2020-03-01                 AT&T                        1
1903994  0010011    2020-04-01                 AT&T                        1
2074654  0010011    2020-05-01                 AT&T                        1
2180164  0010011    2020-06-01                 AT&T                        1
2282306  0010011    2020-07-01                 AT&T                        1
2381478  0010011    2020-08-01                 AT&T                        1
2397244  0010011    2020-09-01                 AT&T                        1
2492765  0010011    2020-10-01                 AT&T                        1
2643951  0010011    2020-11-01                 AT&T                        1
2707118  0010011    2020-12-01                 AT&T                        1
2825161  0010011    2021-01-01                 AT&T                        1
2909917  0010011    2021-02-01                 AT&T                        1
3020245  0010011    2021-03-01                 AT&T                        1
3085253  0010011    2021-04-01                 AT&T                        1
3170181  0010011    2021-05-01                 AT&T                        1
3233777  0010011    2021-06-01                 AT&T                        1
3334680  0010011    2021-07-01                 AT&T                        1
3369088  0010011    2021-08-01                 AT&T                        1
3446676  0010011    2021-09-01                 AT&T                        1
3526602  0010011    2021-10-01                 AT&T                        1
3655188  0010011    2021-11-01                 AT&T                        1
3732724  0010011    2021-12-01                 AT&T                        1
3771333  0010011    2022-01-01                 AT&T                        1
3813609  0010011    2022-02-01                 AT&T                        1
3870944  0010011    2022-03-01                 AT&T                        1
3995063  0010011    2022-04-01                 AT&T                        1
4024867  0010011    2022-05-01                 AT&T                        1
4094053  0010011    2022-06-01                 AT&T                        1
4160472  0010011    2022-07-01                 AT&T                        1
4177967  0010011    2022-08-01                 AT&T                        1
4242902  0010011    2022-09-01                 AT&T                        1
4315028  0010011    2022-10-01                 AT&T                        1
4372371  0010011    2022-11-01                 AT&T                        1
4426628  0010011    2022-12-01                 AT&T                        1
4463543  0010011    2023-01-01                 AT&T                        1
4489026  0010011    2023-02-01                 AT&T                        1

In [4]:
from load_data import *

# open config.json
with open("config.json") as f:
    config = json.load(f)

# load data
cabs = load_cabs(config)

In [6]:
# convert BILL_MONTH_DT to datetime
cabs['BILL_MONTH_DT'] = pd.to_datetime(cabs['BILL_MONTH_DT'])

In [7]:
cabs.sort_values("BILL_MONTH_DT")[["CLEAN_ID", "BILL_MONTH_DT"]]

                 CLEAN_ID BILL_MONTH_DT
0           DHDC069129ACR    2019-01-01
4        DHEC152160801ATI    2019-01-01
5          DHEC193407CZUC    2019-01-01
6           DHEC252353ATI    2019-01-01
7          DHEC302549RCSR    2019-01-01
...                   ...           ...
8419989      HCGS646427SN    2024-04-01
8419956      HCGS618709SN    2024-04-01
8419958      HCGS618713SN    2024-04-01
8419936      HCGS318004MB    2024-04-01
8510465  50VLXP067408FVNC    2024-04-01

[8555735 rows x 2 columns]